---
mac:
  - macos/**/*

linux:
  - linux/**/*

windows:
  - windows/**/*

slidev:
  - slide/**/*
  - .github/workflows/deploy_slide.yaml
  - .prettierrc
  - .node-version

GitHub Actions:
  - .github/workflows/**/*
  - .github/scripts/**/*
  - .github/dependabot.yml
  - .github/labeler.yml
  - .github/.typos_config.toml
