---
mac:
  - macos/**/*

linux:
  - linux/**/*

windows:
  - windows/**/*

sliedv:
  - slide/**/*

GitHub Actions:
  - .github/workflows/**/*
  - .github/scripts/**/*
  - .github/dependabot.yml
  - .github/labeler.yml
  - .github/.typos_config.toml
