---
# ref: https://sli.dev/guide/hosting.html#vercel
name: Deploy Slide

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3

      # https://github.com/actions/setup-node/issues/206#issuecomment-774538395
      - uses: nodenv/actions/node-version@main
        id: nodenv
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nodenv.outputs.node-version }}'

      - run: |
          npm install
          npm i -g @slidev/cli
          slidev build --base flutter-expensive-native-embedding-journey
        working-directory: slide
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: slide/dist
