---
# ref: https://sli.dev/guide/hosting.html#github-pages
name: Deploy Slide

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
    paths:
      - '.github/workflows/deploy_slide.yaml'
      - 'slide/**'
      - '.prettierrc'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  slidev-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # https://github.com/actions/setup-node/issues/206#issuecomment-774538395
      - uses: nodenv/actions/node-version@main
        id: nodenv
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nodenv.outputs.node-version }}'

      - run: npm run format
      - run: git diff --exit-code

  slidev-build:
    needs: slidev-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # https://github.com/actions/setup-node/issues/206#issuecomment-774538395
      - uses: nodenv/actions/node-version@main
        id: nodenv
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nodenv.outputs.node-version }}'

      - name: slidev build
        working-directory: slide
        run: |
          npm ci
          # https://sli.dev/guide/hosting.html#provide-downloadable-pdf
          npm run build -- --base /${{ github.event.repository.name }}/
          npm run export
          mv slides-export.pdf dist/flutter-expensive-native-embedding-journey.pdf

      - uses: actions/configure-pages@v1
      - uses: actions/upload-pages-artifact@v1
        with:
          path: "./slide/dist/"

  deploy-slide:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: slidev-build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
